clc
clear all
I=imread('/MATLAB Drive/image.jpg')
I1=rgb2gray(I)
subplot(4,2,1)
imshow(I)
title('original image')
BW1=edge(I1,'sobel')
subplot(4,2,2)
imshow(BW1)
title('edge image using sobel method')
BW2=edge(I1,'prewitt')
subplot(4,2,3)
imshow(BW2)
title('edge image using prewitt method')
BW3=edge(I1,'roberts')
subplot(4,2,4)
imshow(BW3)
title('edge image using roberts method')
BW4=edge(I1,'canny')
subplot(4,2,5)
imshow(BW4)
title('edge image using canny method')